Add a Twig `{% element %}` tag to render dynamic HTML element
studiometa/twig-toolkit pull request #1
Opened 2020-12-13 18:52 UTC by titouanmathis

This PR adds more structure to the package and introduce 2 new features: 

- A Twig `{% element %}` tag to render dynamic HTML element
- A `{{ class() }}` Twig function to easily manage classes

Some security checks might needs to be done on the content passed to the `element` tag to avoid security vulnerabilities, but the feature is working.

```twig
{% set tag = 'div' %}
{% element tag with { dataComponent: 'Component', class: call([ 'foo', { bar: true, baz: false } ]) } %}
  Hello world
{% endelement %}

<div data-component="Component" class="foo bar">
  Hello world
</div>
```

2021-01-18 09:49 UTC, perruche commented on README.md
> +{% include '@meta/components/signature.twig' %}
I'm not sure this is making much of a difference,  `{% include '@meta/components/signature.twig' %}` and ` {% include 'templates/components/signature.twig' %} ` are really simillar. 
I also usure about the `@meta` name, because we are using `Studiometa` in namespaces. 

It could be really usefull to be able to shortned it to `{% include '@components/signature.twig' %}`, like in vuejs

2021-01-18 09:53 UTC, perruche commented on README.md
> +#### `{% element '<tag>' with attrs %}`
What about calling it `tag` or `html_tag` ? Maybe `element` is a too vague name ?

2021-01-18 09:55 UTC, perruche commented on tests/Helpers/HtmlTest.php
> +<?php
i guess we should move to pest like in https://github.com/studiometa/wp-toolkit/pull/11 ?

2021-01-18 09:57 UTC, perruche commented on src/Helpers/Template.php
> +        $loader->addPath(__DIR__ . '/../../templates', 'meta');
Unsure about this, is it a problem that the path  is hardcoded ?

2021-01-25 09:37 UTC, lusimeon requested changes
Nice addition, `class() / attributes() / {{ tag }}` are handy! ;)

2021-01-25 09:37 UTC, lusimeon commented on src/Helpers/Html.php
> +            $key = (new Convert($key))->toKebab();
Converting to kebab case (`_` to `-`) can cause troubles for attribute with `_` inside (from third party libraries).
Eg: `<div data-foo_bar="baz"></div>`

Maybe we should just let the key unmodified and wrap it with single quotes.
```
<div {{ attributes({ 'data-foo_bar': { label: 'close' } }) }}></div>
```

2021-01-25 09:37 UTC, lusimeon commented on src/Helpers/Html.php
> +     * @param  array<string|array>|string $class The class description.
`array<string|array>|string` => Is there a typo?

2021-01-25 09:37 UTC, lusimeon commented on src/Helpers/Html.php
> +        $renderedAttributes = [''];
[''] => Is there a typo?

2021-01-25 09:37 UTC, lusimeon commented on tests/Helpers/HtmlTest.php
> +<?php
wp-toolkit use phpunit because of Wordpress version limitation. Here Pest can still be used.

2021-01-25 17:27 UTC, titouanmathis commented on src/Helpers/Html.php
> +     * @param  array<string|array>|string $class The class description.
That is not a typo, the method can be used as follows: 

```php
Html::renderClass('foo'); // string
Html::renderClass(['foo', 'bar']); // array<string>
Html::renderClass(['foo', ['bar' => true, 'baz' => false]]); // array<string|array>
```

2021-01-25 17:32 UTC, titouanmathis commented on src/Helpers/Html.php
> +        $renderedAttributes = [''];
No, it is to make sure to have an empty space before the first rendered attributes. Without it, we might encounter the following error:

```diff
--- Expected
+++ Actual
@@ @@
-'<div aria-hidden="true" data-options="&#x7B;&quot;log&quot;&#x3A;true&#x7D;">
+'<divaria-hidden="true" data-options="&#x7B;&quot;log&quot;&#x3A;true&#x7D;">
     Hello world
 </div>'
```

2021-01-25 17:34 UTC, titouanmathis commented on src/Helpers/Template.php
> +        $loader->addPath(__DIR__ . '/../../templates', 'meta');
The path is hard coded to expose templates from this package under the `@meta` alias, this is more a feature than a bug 🙂

2021-01-25 17:41 UTC, titouanmathis commented on README.md
> +#### `{% element '<tag>' with attrs %}`
It might not be the best name, indeed. I am not quite sure about a name using `tag`, as it does more than just print a tag.

Maybe `html_element` would be more clear?

2021-01-25 17:47 UTC, titouanmathis commented on src/Helpers/Html.php
> +            $key = (new Convert($key))->toKebab();
The conversion to kebab-case is indeed opinionated, but it alos seems to be the most popular way of writing attributes. I figured the benefits outweighed the drawbacks, as custom attributes could be added separately:

```twig
<div {{ attributes({ data_foo: true }) }} data-foo_bar="value"></div>
```

2021-01-25 18:52 UTC, lusimeon approved these changes

2021-01-31 12:21 UTC, titouanmathis commented on README.md
> +#### `{% element '<tag>' with attrs %}`
I changed the name to `html_element` to be more clear:

```twig
{% html_element 'div' %}
  <span>Hello world</span>
{% end_html_element %}
```

2021-01-31 12:24 UTC, merged